- name: Get mig controller information
  k8s_facts:
    api_version: migration.openshift.io/v1alpha1
    kind: MigrationController
    name: migration-controller
    namespace: "{{ migration_namespace }}"
  register: mig_controller
  until: mig_controller.resources | length > 0

- name: Store controller config
  set_fact:
    previous_namespace_limit: "{{ (mig_controller.resources|first).spec.get('mig_namespace_limit', 100) }}"

- name: Update mig controller
  k8s:
    api_version: migration.openshift.io/v1alpha1
    namespace: "{{ migration_namespace }}"
    definition: "{{ (mig_controller.resources|first) | combine({ 'spec': {'mig_namespace_limit': namespace_limit } }) }}"

- pause:
    prompt: Wait 1 minute for controller reconciliation
    minutes: 1

- name: Execute migration
  include_role:
    name: migration_run

