- name: Include required vars
  include_vars:
    file: "{{ playbook_dir }}/config/mig_controller.yml"

- name: Create migration plan
  k8s:
    state: present
    definition: "{{ lookup('template', 'mig-plan.yml.j2') }}"

- debug:
    msg: "Created migration plan : {{ migration_plan_name }}"

- name: Process PVs
  import_tasks: process_pvs.yml
  when: pv|default(false)|bool == true

# Fix me: https://github.com/fusor/mig-controller/issues/84
- name: Allow velero to reconcile changes before attempting migration
  pause:
    seconds: "{{ mig_velero_timeout }}"
  when: mig_velero_pause is not defined

- set_fact:
    mig_velero_pause: true

- name: Get plan information when ready
  k8s_facts:
    kind: MigPlan
    api_version: v1alpha1
    namespace: "{{ migration_namespace }}"
    name: "{{ migration_plan_name }}"
  register: mig_plan
  until: mig_plan.resources|length > 0 and (mig_plan.resources[0].get( 'status', {}).get("conditions", {}) | selectattr( 'type', 'equalto', 'Ready') | selectattr( 'status', 'equalto', 'True') | list | length > 0)
  retries: 10
  delay: 5

- name: Expose migplan fact
  set_fact:
    fact_migrated_plan: "{{ mig_plan.resources | first }}"

- name: Process staged migration phase
  import_tasks: stage.yml
  when: stage|default(false)|bool == true

- name: Execute migration
  k8s:
    state: present
    definition: "{{ lookup('template', 'mig-migration.yml.j2') }}"

- debug:
    msg: "Created migration name : {{ migration_name }}"
