- name: Cleanup resources
  include_role:
    name: migration_cleanup
  when: with_cleanup|bool

- name: Disable ceph storage classes
  import_tasks: disable_ceph.yml
  when: with_migrate|bool and disable_ceph is defined and disable_ceph|bool

- name: Create resources
  import_tasks: deploy.yml
  when: with_deploy|bool

- name: Start migration
  import_tasks: migrate.yml
  when: with_migrate|bool

- name: Validate default storageclasses
  import_tasks: common_tasks/validate-defaults.yml
  when: ((with_validate|bool) and (with_migrate|bool)) or (with_validate_source|default(false)|bool)

- name: Track migration
  import_tasks: track.yml
  when: with_migrate|bool

- name: Validate source
  import_tasks: validate-source.yml
  when: ((with_validate|bool) and (with_deploy|bool)) or (with_validate_source|default(false)|bool)

- name: Validate migration
  import_tasks: validate-target.yml
  when: ((with_validate|bool) and (with_migrate|bool)) or (with_validate_target|default(false)|bool)

- name: Restore ceph storage classes
  import_tasks: restore_ceph.yml
  when: with_migrate|bool and disable_ceph is defined and disable_ceph|bool
