- name: Get storage classes
  k8s_info:
    kind: StorageClass
  register: storage_classes
  until: storage_classes.resources[0]  | length > 0

- name: Restore original ceph storage classes
  k8s:
    state: present
    definition: "{{ scitem | combine({'metadata':{'name': scitem.metadata.name|replace('-modified', '')}, 'provisioner': scitem.provisioner | replace('xxxxxx', 'ceph')})  | to_yaml}}"
  when: '"xxxxxx" in scitem.provisioner'
  loop: "{{ storage_classes.resources }}"
  loop_control:
    loop_var: scitem

- name: Delete fake ceph storage classes
  k8s:
    state: absent
    definition: "{{ scitem | to_yaml}}"
  when: '"xxxxxx" in scitem.provisioner'
  loop: "{{ storage_classes.resources }}"
  loop_control:
    loop_var: scitem
