- name: "Check if migration {{ migration_name }} has a warning"
  k8s_facts:
    kind: MigPlan
    api_version: v1alpha1
    namespace: "{{ migration_namespace }}"
    name: "{{ migration_plan_name }}"
  register: mig_plan
  until:  mig_plan.resources[0].status.get('conditions', {}) | list | selectattr( "type", "equalto", "PodLimitExceeded") | selectattr( "category", "equalto", "Warn") | list | length > 0
  retries: 5

- name: "Max-pods warning found"
  debug: 
    msg: "{{ mig_plan.resources[0].status.get('conditions', {}) | list | selectattr( 'type', 'equalto', 'PodLimitExceeded') | selectattr( 'category', 'equalto', 'Warn') | list }}"


- name: Get mig controller information to restore the original limit
  k8s_facts:
    api_version: migration.openshift.io/v1alpha1
    kind: MigrationController
    name: migration-controller
    namespace: "{{ migration_namespace }}"
  register: mig_controller
  until: mig_controller.resources | length > 0

- name: Restore mig controller initial limit values
  k8s:
    api_version: migration.openshift.io/v1alpha1
    namespace: "{{ migration_namespace }}"
    definition: "{{ (mig_controller.resources|first) | combine({ 'spec': {'mig_pod_limit': previous_pod_limit|int } }) }}"
