- hosts: localhost
  roles:
    - { role: migration_prepare, tags: ["always"] }
    - { role: mssql-app, tags: ["mssql-app"], pv_action: 'copy', stage: 'true', dst_storage_class: 'ocs-storagecluster-cephfs' }
    - { role: sock-shop, tags: ["sock-shop"] }
    - { role: robot-shop, tags: ["robot-shop"] }
    - { role: parks-app, tags: ["parks-app"], pv_action: 'copy', src_storage_class: 'glusterfs-storage' }
    - { role: mediawiki, tags: ["never", "mediawiki"], pv_action: 'copy', src_storage_class: 'glusterfs-storage', dst_storage_class: 'ocs-storagecluster-cephfs' }
    - { role: ocp-25000-sets, tags: ["ocp-25000-sets", "ocp"] }
    - { role: ocp-25021-cronjob, tags: ["never", "ocp-25021-cronjob"] }
    - { role: ocp-25090-jobs, tags: ["ocp-25090-jobs", "ocp"] }
    - { role: ocp-25212-initcont, tags: ["ocp-25212-initcont", "ocp"] }
    - { role: ocp-24997-confmap, tags: ["ocp-24997-confmap", "ocp"] }
    - { role: ocp-24995-role, tags: ["ocp-24995-role", "ocp"] }
    - { role: ocp-25986-maxpods, tags: ["ocp-25986-maxpods", "ocp"] }
    - { role: nginx-pv, tags: ["nginx-pv", "ocp"] }
    - { role: ocp-24659-mysql, tags: ["ocp-24659-mysql", "ocp"] }
    - { role: ocp-24686-project, tags: ["ocp-24686-project", "ocp"] }
    - { role: ocp-24769-cakephp, tags: ["ocp-24769-cakephp", "ocp"] }
    # 3.7 -> 4.x migration failing for django because 9.5 postgres image does not exist in 4.x
    - { role: ocp-24730-django, tags: ["never", "ocp-24730-django"] }
    - { role: ocp-26032-maxns, tags: ["ocp-26032-maxns", "ocp"] }
    - { role: ocp-26160-max-pvs, tags: ["ocp-26160-max-pvs", "ocp"] }
    - { role: ocp-24787-redis, tags: ["ocp-24787-redis", "ocp"] }
    - { role: ocp-24797-mongodb, tags: ["ocp-24797-mongodb", "ocp"] }
  vars_files:
    - "{{ playbook_dir }}/config/mig_controller.yml"
    - "{{ playbook_dir }}/config/defaults.yml"
