- hosts: localhost
  vars:
    platform_sc: gp2
  roles:
    - role: nginx-pv
      namespace: "ng-cloud2cloud"
      src_storage_class: "{{ platform_sc }}"
      dst_storage_class: "{{ platform_sc }}"
      pv: true
    - role: nginx-pv
      namespace: "ng-cloud2rbd"
      src_storage_class: "{{ platform_sc }}"
      dst_storage_class: "csi-rbd"
      pv: true
    - role: nginx-pv
      namespace: "ng-cloud2cfs"
      src_storage_class: "{{ platform_sc }}"
      dst_storage_class: "csi-cephfs"
      pv: true
    - role: nginx-pv
      namespace: "ng-cloud2nfs"
      src_storage_class: "{{ platform_sc }}"
      dst_storage_class: "nfs"
      pv: true
    - role: nginx-pv
      namespace: "ng-gfs2def-noceph"
      src_storage_class: "glusterfs-storage"
      disable_ceph: true
      pv: false
    - role: nginx-pv
      namespace: "ng-gfs2def"
      src_storage_class: "glusterfs-storage"
      pv: false
    - role: nginx-pv
      namespace: "ng-gblock2def"
      src_storage_class: "glusterfs-storage-block"
      pv: false
    - role: nginx-pv
      namespace: "ng-gfs2cloud"
      src_storage_class: "glusterfs-storage"
      dst_storage_class: "{{ platform_sc }}"
      pv: true
    - role: nginx-pv
      namespace: "ng-gblock2cloud"
      src_storage_class: "glusterfs-storage-block"
      dst_storage_class: "{{ platform_sc }}"
      pv: true
    - role: nginx-pv
      namespace: "ng-nfs2def"
      src_storage_class: "nfs"
      html_accessmode: ReadWriteMany
      pv: false
    - role: nginx-pv
      namespace: "ng-nfs2cloud"
      src_storage_class: "nfs"
      dst_storage_class: "{{ platform_sc }}"
      pv: true
  vars_files:
    - "{{ playbook_dir }}/config/mig_controller.yml"
    - "{{ playbook_dir }}/config/defaults.yml"
