- hosts: localhost
  vars:
    platform_sc: gp2
  #roles:

  tasks:
  - include_role:
      name: migration_prepare

  # include_role is bugged, and does not honor the tags. We encapsulate it in a "block" so taht tags can be honored.
  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-cloud2cloud"
        src_storage_class: "{{ platform_sc }}"
        dst_storage_class: "{{ platform_sc }}"
        pv: true
        no_warnings_allowed:  false
    tags: [ ng-cloud2cloud, source_cloud, target_cloud ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-cloud2rbd"
        src_storage_class: "{{ platform_sc }}"
        dst_storage_class: "csi-rbd"
        pv: true
    tags: [ ng-cloud2rbd ,source_cloud, target_ceph, target_cephrbd ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-cloud2cfs"
        src_storage_class: "{{ platform_sc }}"
        dst_storage_class: "csi-cephfs"
        pv: true
    tags: [ ng-cloud2cfs, source_cloud, target_ceph, target_cephfs ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-cloud2nfs"
        src_storage_class: "{{ platform_sc }}"
        dst_storage_class: "nfs"
        pv: true
    tags: [ ng-cloud2nfs, source_cloud, target_nfs ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-gfs2cloud"
        src_storage_class: "glusterfs-storage"
        dst_storage_class: "{{ platform_sc }}"
        pv: true
    tags: [ ng-gfs2cloud, source_glusterfs, source_gfs-storage, target_cloud ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-gblock2cloud"
        src_storage_class: "glusterfs-storage-block"
        dst_storage_class: "{{ platform_sc }}"
        pv: true
    tags: [ ng-gblock2cloud, source_glusterfs, source_gfs_storage_block, target_cloud ]


  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-nfs2nfs"
        src_storage_class: "nfs"
        dst_storage_class: "nfs"
        html_accessmode: ReadWriteMany
        pv: true
        # BZ https://bugzilla.redhat.com/show_bug.cgi?id=1761483 
        # We have a warning here, but the migration must be fine.
        no_warnings_allowed:  false
    tags: [ ng-nfs2nfs, source_nfs, target_nfs ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-nfs2def"
        src_storage_class: "nfs"
        html_accessmode: ReadWriteMany
        pv: false
    tags: [ ng-nfs2def, source_nfs, target_default ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-noceph-nfs2def"
        src_storage_class: "nfs"
        disable_ceph: true
        pv: false
    tags: [ ng-noceph-nfs2def, source_nfs, target_default ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-nfs2cloud"
        src_storage_class: "nfs"
        dst_storage_class: "{{ platform_sc }}"
        pv: true
    tags: [ ng-nfs2cloud, source_nfs, target_cloud ]


  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-gfs2def"
        src_storage_class: "glusterfs-storage"
        html_accessmode: ReadWriteMany
        pv: false
    tags: [ ng-gfs2def, source_glusterfs, source_gfs-storage, target_default ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-gfs2cephrbd"
        src_storage_class: "glusterfs-storage"
        dst_storage_class: "csi-rbd"
        pv: true
    tags: [ ng-gfs2cephrbd, source_glusterfs, source_gfs-storage, target_ceph, target_cephrbd]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-noceph-gfs2def"
        src_storage_class: "glusterfs-storage"
        disable_ceph: true
        pv: false
    tags: [ ng-noceph-gfs2def, source_glusterfs, source_gfs-storage, target_default ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-gblock2def"
        src_storage_class: "glusterfs-storage-block"
        pv: false
    tags: [ ng-gblock2def, source_glusterfs, source_gfs_storage_block, target_default ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-noceph-gblock2def"
        src_storage_class: "glusterfs-storage-block"
        disable_ceph: true
        pv: false
    tags: [ ng-noceph-gblock2def, source_glusterfs, source_gfs_storage_block, target_default ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-gblock2cephfs"
        src_storage_class: "glusterfs-storage-block"
        dst_storage_class: "csi-cephfs"
        pv: true
    tags: [ng-gblock2cephfs , source_glusterfs, source_gfs_storage_block, target_ceph, target_cephfs ]

  - block:
    - include_role:
        name: nginx-pv
      vars:
        namespace: "ng-nfsmove"
        src_storage_class: ""
        pv_action: move
        pv: true
    tags: [never , move]


  vars_files:
    - "{{ playbook_dir }}/config/mig_controller.yml"
    - "{{ playbook_dir }}/config/defaults.yml"
