- hosts: localhost
  roles:
    - { role: migration_prepare, tags: ["always"] }
    - { role: stateless, tags: ["stateless"] }
    - { role: local-images, tags: ["local-images"] }
    - { role: nfs-pv, tags: ["nfs-pv"] }
  vars_files:
    - "{{ playbook_dir }}/config/mig_controller.yml"
