namespace: ocp-24871-datagrid

num_dg_instances: 1
app_password: changeme
app_user: test
hotrod_client_sourcecode: "https://raw.githubusercontent.com/sergiordlr/temp-testfiles/master/app_migration/datagrid/template_hotrod_client.yml"
cronjob_insert_sourcecode: "https://raw.githubusercontent.com/sergiordlr/temp-testfiles/master/app_migration/datagrid/cronjob_template.yml"
cron_name: rest-insert
rest_cache_name: "restcache"
hotrod_cache_name: "hotrodcache"

migration_sample_name: "{{ namespace }}"
migration_plan_name: "{{ migration_sample_name }}-migplan-{{ ansible_date_time.epoch }}"
migration_name: "{{ migration_sample_name }}-mig-{{ ansible_date_time.epoch }}"
#migration_sample_files: "{{ playbook_dir }}/mig-controller/docs/scenarios/{{ migration_sample_name }}"
with_deploy: true
with_migrate: true
with_cleanup: true
with_validate: true
pv: false
quiesce: false
