- name: Check namespace
  k8s_facts:
    kind: Namespace
    name: "{{ namespace }}"
  register: ns

- name: Create namespace
  shell: "{{ oc_binary }} new-project {{ namespace }} --skip-config-write=true"
  when: ns.resources | length == 0

- name: Create openshift redis application from openshift templates
  shell: "{{ oc_binary }} -n {{ namespace }} new-app --template redis-persistent -p REDIS_PASSWORD={{ redis_password }}"
