---
namespace: ocp-24686-project

project_region: west_region
project_label:  ocp-24686-label


migration_sample_name: "{{ namespace }}"
migration_plan_name: "{{ migration_sample_name }}-migplan-{{ ansible_date_time.epoch }}"
migration_name: "{{ migration_sample_name }}-mig-{{ ansible_date_time.epoch }}"
#migration_sample_files: "{{ playbook_dir }}/mig-controller/docs/scenarios/{{ migration_sample_name }}"
with_deploy: true
with_migrate: true
with_cleanup: true
with_validate: true
