- name: Check namespace
  k8s_facts:
    kind: Namespace
    name: "{{ namespace }}"
  register: ns

- name: Create namespace
  shell: "{{ oc_binary }} new-project {{ namespace }}  --skip-config-write=true"
  when: ns.resources | length == 0

- name: Import image to imagestream
  shell: "{{ oc_binary }} -n {{ namespace }}  import-image {{ internal_image_name }}:{{ internal_image_tag }} --from {{ external_image_name }} --confirm"

- name: Deploy job using external image
  k8s:
    state : present
    namespace : "{{ namespace }}"
    definition: "{{ lookup('template', 'deployment.yml.j2' )}}"
  vars:
    app_name: "{{ ext_app_name }}"
    sleep_time: 1d
    docker_image: docker.io/alpine


- name: Deploy job using internal image
  k8s:
    state : present
    namespace : "{{ namespace }}"
    definition: "{{ lookup('template', 'deployment.yml.j2' )}}"
  vars:
    app_name: "{{ int_app_name }}"
    sleep_time: 1d
    docker_image: "docker-registry.default.svc:5000/{{ namespace }}/{{ internal_image_name }}:{{ internal_image_tag }}"


- name: Deploy fast job using external image. This fob will end and should not be migrated
  k8s:
    state : present
    namespace : "{{ namespace }}"
    definition: "{{ lookup('template', 'deployment.yml.j2' )}}"
  vars:
    app_name: "{{ fast_app_name }}"
    sleep_time: 1
    docker_image: docker.io/alpine
