- name: Check namespace
  k8s_facts:
    kind: Namespace
    name: "{{ namespace }}"
  register: ns

- name: Create namespace
  shell: "{{ oc_binary }} new-project {{ namespace }} --skip-config-write=true"
  when: ns.resources | length == 0

- name: Create openshift mongodb application from openshift templates
  shell: "{{ oc_binary }} -n {{ namespace }} new-app --template mongodb-persistent -p MONGODB_USER={{ mongodb_user }} -p MONGODB_PASSWORD={{ mongodb_pass }}"
